## cluster数据源配置
cluster:
    datasource:
           url: jdbc:mysql://localhost:3306/sb?useUnicode=true&characterEncoding=utf8
           username: root
           password: 90755
           driver-class-name: com.mysql.jdbc.Driver
## master数据源配置
master:
      datasource:
          url: jdbc:mysql://localhost:3306/sb1?useUnicode=true&characterEncoding=utf8
          username: root
          password: 90755
          driver-class-name: com.mysql.jdbc.Driver
## Mybatis 配置
##mybatis:
##   typeAliasesPackage: org.spring.springboot.domain
##   mapperLocations: classpath:mapper/*.xml

##  mybatis.config = mybatis 配置文件名称
##  mybatis.mapperLocations = mapper xml 文件地址
##  mybatis.typeAliasesPackage = 实体类包路径
##  mybatis.typeHandlersPackage = type handlers 处理器包路径
##  mybatis.check-config-location = 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
##  mybatis.executorType = 执行模式。默认是 SIMPLE